/** Every user-facing string in one place. */

const plural = (n: number, one: string, many: string): string => `${n} ${n === 1 ? one : many}`;

export const S = {
  app: {
    name: 'soulsaka',
    tagline: 'a private clone of you, on your own hardware',
  },
  nav: {
    capture: 'Capture',
    chat: 'Chat',
    memories: 'Memories',
    corpus: 'Corpus',
    train: 'Train',
    settings: 'Settings',
  },
  conn: {
    live: 'Live',
    connecting: 'Connecting',
    down: 'Hub unreachable',
    offline: 'Offline',
    unauthorized: 'Not paired',
  },
  banners: {
    offline: 'You are offline. Captures are kept on this device and upload when the hub is back.',
    hubDown: 'The hub is not reachable right now. Captures are queued on this device.',
    pending: (n: number) => `${plural(n, 'capture', 'captures')} waiting to upload`,
    retryNow: 'Retry now',
  },
  errors: {
    network: 'Could not reach the hub.',
    generic: 'Something went wrong.',
    notImplemented: 'This hub does not have that endpoint yet.',
    unauthorized: 'This device is not paired with the hub.',
    micDenied: 'Microphone access was refused. Allow it in the browser settings and try again.',
    micUnsupported: 'This browser cannot record audio.',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    archive: 'Archive',
    unarchive: 'Restore',
    edit: 'Edit',
    copy: 'Copy',
    copied: 'Copied',
    retry: 'Retry',
    refresh: 'Refresh',
    loading: 'Loading',
    close: 'Close',
    none: 'none',
    unknown: 'unknown',
    confirmDelete: 'Delete this? It cannot be undone.',
    yes: 'Yes',
    no: 'No',
    on: 'On',
    off: 'Off',
    words: (n: number) => plural(n, 'word', 'words'),
    items: (n: number) => plural(n, 'item', 'items'),
  },
  pair: {
    title: 'Pair this device',
    lead: 'Enter the 8-character code shown by `soulsaka serve` or `soulsaka pair` on the hub, or under Settings on a paired device.',
    codeLabel: 'Pairing code',
    nameLabel: 'Name this device',
    namePlaceholder: 'e.g. iPhone',
    submit: 'Pair',
    pairing: 'Pairing',
    invalid: 'That code is invalid or has expired. Mint a new one on the hub and try again.',
    hubLabel: 'Hub address',
    hubHint: 'Leave empty to use the address this page was loaded from.',
    hubPlaceholder: 'http://192.168.1.20:8765',
    localHint: 'On the hub machine itself, open the app at http://127.0.0.1:8765 and no code is needed.',
  },
  capture: {
    title: 'Capture',
    sub: 'Notes and speech go into your corpus. Say "remember …" and it becomes a memory on every device.',
    textPlaceholder: 'Type a note, or "remember …"',
    send: 'Send',
    ptt: 'Hold to talk',
    pttTap: 'Tap to stop',
    pttHint: 'Hold, or tap once to start and again to stop',
    recording: 'Recording',
    listening: 'Listening',
    alwaysListening: 'Always listening',
    alwaysListeningHint:
      'Keeps the microphone open and uploads only the moments with speech. Speech that is not your voice is discarded on the hub.',
    sensitivity: 'Sensitivity',
    level: 'Level',
    segmentSent: 'segment sent',
    recent: 'Recent captures',
    empty: 'Nothing captured yet. Type a note or hold the button and talk.',
    transcriptPending: 'Waiting for the hub',
    transcriptProcessing: 'Transcribing',
    discardedOther: 'Not your voice; discarded',
    discardedSilence: 'No speech found',
    memoriesLinked: (n: number) => plural(n, 'memory', 'memories'),
    speakerMe: 'me',
    speakerNotMe: 'not me',
    speakerUnknown: 'unknown speaker',
    origin: { manual: 'typed', listener: 'listener', chat: 'chat' } as Record<string, string>,
    kindAudio: 'voice',
    kindText: 'text',
    retry: 'Retry',
    remove: 'Remove',
    queued: 'queued on this device',
    status: {
      queued: 'queued',
      pending: 'pending',
      processing: 'processing',
      done: 'done',
      discarded: 'discarded',
      failed: 'failed',
    } as Record<string, string>,
    keepScreenOn: 'Keep this screen open while listening; browsers stop the microphone in the background.',
  },
  chat: {
    title: 'Chat',
    newChat: 'New chat',
    chats: 'Chats',
    noChats: 'No chats yet.',
    untitled: 'Untitled chat',
    placeholder: 'Message',
    placeholderTwin: 'Say something to yourself',
    send: 'Send',
    stop: 'Stop',
    modeAssistant: 'Assistant',
    modeTwin: 'Twin',
    modeHintAssistant: 'A helper that knows your memories.',
    modeHintTwin: 'Replies the way you would.',
    register: 'Register',
    registers: { text: 'text', email: 'email', speech: 'speech', doc: 'doc' } as Record<string, string>,
    profile: 'Model',
    cloud: 'cloud',
    personal: 'your adapter',
    cloudDisabled: 'Cloud profiles are off. Set privacy.allow_cloud_llm = true in config.toml to allow them.',
    cloudReply: 'This reply came from a cloud model.',
    errCloudRefused: 'That profile would send your prompt off this machine. It is refused until privacy.allow_cloud_llm is switched on.',
    errModelDown: (profile: string) =>
      `The model behind "${profile}" is not answering. Start llama.cpp or Ollama on the hub, then try again.`,
    errEmpty: 'Type something first.',
    thinking: 'Thinking',
    emptyThread: 'Start a conversation. In twin mode, ask what you would say.',
    selectChat: 'Pick a chat or start a new one.',
  },
  memories: {
    title: 'Memories',
    sub: 'Durable facts the assistant should know. Spoken notes land here within seconds.',
    search: 'Search memories',
    add: 'Add a memory',
    addPlaceholder: 'e.g. Parking spot is B12 this week',
    kind: 'Kind',
    save: 'Save',
    empty: 'No memories yet. Say "remember …" on any device, or add one here.',
    noResults: 'Nothing matches that search.',
    showArchived: 'Show archived',
    archived: 'archived',
    kinds: {
      note: 'Notes',
      fact: 'Facts',
      preference: 'Preferences',
      todo: 'To do',
      number: 'Numbers',
      event: 'Events',
      person: 'People',
    } as Record<string, string>,
    kindSingular: {
      note: 'note',
      fact: 'fact',
      preference: 'preference',
      todo: 'to do',
      number: 'number',
      event: 'event',
      person: 'person',
    } as Record<string, string>,
    source: { explicit: 'said', manual: 'added', llm: 'extracted' } as Record<string, string>,
  },
  corpus: {
    title: 'Corpus',
    sub: 'Everything the model learns from is your own words.',
    wordsOfYou: 'words of you',
    messages: 'messages',
    contextMessages: 'context messages from others',
    conversations: 'conversations',
    memories: 'memories',
    pendingCaptures: 'captures pending',
    latestVersion: 'latest adapter',
    firstTrain: 'first train',
    comfortable: 'comfortable',
    readyToTrain: 'Enough to train a first version.',
    needMore: (n: number) => `${n.toLocaleString()} more words until a first train.`,
    byRegister: 'By register',
    bySource: 'By source',
    byMonth: 'By month',
    languages: 'Languages',
    register: 'register',
    source: 'source',
    words: 'words',
    sources: 'Sources',
    noSources: 'No sources yet. Import your history from the Mac, or drop an export below.',
    deleteSource: 'Delete',
    confirmDeleteSource: (label: string) =>
      `Delete "${label}" and all of its messages from the corpus?`,
    lastImport: 'last import',
    upload: 'Drop an export',
    uploadHint:
      'WhatsApp .txt or .zip exports, Discord data packages (.zip), mailbox files (.mbox), or a copied chat database (chat.db, ChatStorage.sqlite).',
    uploadPick: 'Choose a file',
    uploadKind: 'Format',
    uploadKinds: {
      auto: 'Detect automatically',
      whatsapp_export: 'WhatsApp export (.txt / .zip)',
      discord: 'Discord package (.zip)',
      mbox: 'Mailbox (.mbox)',
      imessage: 'iMessage database (chat.db)',
      whatsapp: 'WhatsApp database (ChatStorage.sqlite)',
      emlx: 'Apple Mail (.emlx)',
    } as Record<string, string>,
    uploading: 'Uploading',
    uploadUnavailable: 'This hub cannot take uploads yet. Use the command line instead.',
    report: 'Import report',
    reportInserted: 'inserted',
    reportDuplicates: 'duplicates',
    reportSkipped: 'skipped',
    reportMeWords: 'words of you',
    reportConversations: 'conversations',
    reportNotes: 'notes',
    importCli: 'Import from your Mac',
    importCliLead: 'iMessage, WhatsApp and Mail live on the Mac. Pair it once, then let the importer find them.',
    getCode: 'Get a pairing code',
    codeValid: 'valid for 10 minutes',
    noMonths: 'No dated messages yet.',
    wordsPerMonth: 'words per month',
  },
  train: {
    title: 'Train',
    sub: 'Cumulative retrains from the base model into versioned adapters.',
    versions: 'Adapter versions',
    noRuns: 'No training runs yet. Build the corpus past the first-train mark, then start one here.',
    preview: 'Preview dataset',
    previewTitle: 'Dataset preview',
    previewSummary: (ex: number, words: number, holdout: number) =>
      `${ex.toLocaleString()} examples, ${words.toLocaleString()} target words, ${holdout.toLocaleString()} held out`,
    previewSystem: 'system',
    previewTarget: 'you',
    trainNext: 'Train next version',
    training: 'A run is in progress',
    started: (v: string) => `Started ${v}.`,
    unavailable: 'Training is not available on this hub yet.',
    fidelity: 'Fidelity by version',
    fidelitySub:
      'Blind accuracy and discriminator accuracy should fall toward 50%: at that point nobody can tell you apart.',
    noEval: 'No evaluations yet. They appear here after the first adapter is trained and rated.',
    seriesBlind: 'Blind guesses',
    seriesDisc: 'Discriminator',
    seriesVoice: 'Voice similarity',
    target: 'target 50%',
    status: {
      planned: 'planned',
      running: 'running',
      done: 'done',
      failed: 'failed',
    } as Record<string, string>,
    examples: 'examples',
    words: 'words',
    cutoff: 'data through',
    base: 'base',
    backend: 'backend',
    metrics: 'metrics',
    error: 'error',
    rateLink: 'Blind test link',
    rateHint: 'Send this to a friend who knows how you write.',
  },
  rate: {
    title: 'Which one is real?',
    lead: (name: string) => `One of each pair was written by ${name}; the other by a model. Pick the real one.`,
    leadNoName: 'One of each pair was written by a real person; the other by a model. Pick the real one.',
    yourName: 'Your name',
    namePlaceholder: 'so we can count your guesses',
    start: 'Start',
    context: 'Context',
    first: 'A',
    second: 'B',
    correct: 'Right',
    wrong: 'Nope',
    next: 'Next',
    progress: (i: number, n: number) => `${i} of ${n}`,
    done: 'That is all of them',
    score: (c: number, n: number) => `${c} of ${n} right`,
    interpret: (pct: number) =>
      pct <= 55
        ? 'Around 50% means you could not tell. That is the goal.'
        : pct <= 70
          ? 'You caught the model more often than chance. There is still work to do.'
          : 'The model is easy to spot at this version.',
    noPairs: 'No pairs to rate for this version yet.',
    unavailable: 'This hub does not serve blind pairs yet.',
    again: 'Rate more',
    version: 'version',
    overall: (c: number, n: number) => `All of your guesses for this version so far: ${c} of ${n}.`,
  },
  settings: {
    title: 'Settings',
    device: 'This device',
    deviceName: 'name',
    deviceKind: 'kind',
    deviceUid: 'id',
    paired: 'paired',
    lastSeen: 'last seen',
    localDevice: 'This browser is on the hub machine and is trusted without a token.',
    forget: 'Forget this device',
    hub: 'Hub',
    hubUrl: 'Hub address',
    hubHint: 'Empty means the address this page came from. Set it when running the dev server.',
    hubSaved: 'Saved. Reloading.',
    pairAnother: 'Pair another device',
    pairLead: 'Mint a code, then open the link on the other device or type the code there.',
    mint: 'New pairing code',
    minting: 'Minting',
    codeExpires: (min: number) => `expires in ${min} min`,
    openOn: 'Open on the new device',
    devices: 'Paired devices',
    noDevices: 'No paired devices.',
    revoke: 'Revoke',
    confirmRevoke: (name: string) => `Revoke "${name}"? It will need to pair again.`,
    speaker: 'Voice profile',
    speakerLead: 'The hub only keeps speech that matches your enrolled voice.',
    enrolled: 'enrolled',
    notEnrolled: 'not enrolled',
    ready: 'ready',
    notReady: (n: number, min: number) =>
      `${n} of ${min} samples. Use push-to-talk a few times to enroll.`,
    samples: 'samples',
    threshold: 'threshold',
    backend: 'backend',
    resetSpeaker: 'Reset voice profile',
    voice: 'Voice',
    voiceLead:
      'The voice clone imitates a reference clip of your own speech, stitched from push-to-talk captures the hub has transcribed.',
    voiceReference: 'reference clip',
    voiceReady: 'built',
    voiceNone: 'not built yet',
    voiceCandidates: 'usable clips',
    voiceText: 'transcript',
    voiceBuild: 'Build reference clip',
    voiceBuilt: (s: number) => `Built a ${s.toFixed(0)} s reference clip.`,
    voicePlay: 'Play reference',
    voiceSayPlaceholder: 'Something to hear in your voice',
    voiceSpeak: 'Speak',
    voiceUnavailable: 'Voice synthesis is not set up on this hub.',
    confirmResetSpeaker: 'Reset the voice profile? The next push-to-talk captures will re-enroll it.',
    privacy: 'Privacy',
    privacyOther: 'Other speakers',
    privacyOtherValues: { discard: 'discarded', context_only: 'kept as context only' } as Record<string, string>,
    privacyAudio: 'Keep my audio',
    privacyCloud: 'Cloud models',
    privacyCloudOn: 'allowed',
    privacyCloudOff: 'refused',
    privacyNames: 'Contact names',
    privacyNamesOn: 'kept',
    privacyNamesOff: 'hashed only',
    privacyEdit: 'Change these in config.toml on the hub.',
    llm: 'Model profiles',
    llmDefault: 'default',
    llmProfile: 'profile',
    llmModel: 'model',
    jobs: 'Background jobs',
    jobsNone: 'No jobs recorded.',
    jobsCounts: 'by status',
    jobsRecent: 'recent',
    theme: 'Appearance',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    about: 'About',
    version: (v: string) => `hub ${v}`,
    asr: 'transcription',
    trainBase: 'base model',
    me: 'You',
    meNames: 'names',
  },
} as const;
